### ISSUE TITLE
Question: Holes and quality mesh features

### ISSUE THREAD

**Issue by michelk** [hugoledoux/startin#13]
Currently for meshing I use the command-line tool [triangle](https://www.cs.cmu.edu/~quake/triangle.html).

Is it planned to also implement holes, regions (region-ids) or quality-mesh features (per-region area restrictions, min. angle, ...)

**Comment by hugoledoux** [comment]
Triangle is a constrained triangulator, and startin has no constraints yet.

Triangle has a different purpose really, meshing a domain for further processing. 

startin is a triangulator for terrains.

**Comment by michelk** [comment]
ok thanks for clarification.
