### ISSUE TITLE
if duplicates, then let user choose which z-value should be kept

### ISSUE THREAD

**Issue by hugoledoux** [hugoledoux/startin#22]
- first
- latest
- highest
- lowest
- average is not possible I guess

**Comment by evetion** [comment]
Could you clarify the context? What duplicates, in what call?

**Comment by hugoledoux** [comment]
duplicates in x-y so insertion where a vertex already exists. 

Right now the first insertion is what stays, but some applications (creation of a DSM eg) would benefit from another behaviour.

**Comment by hugoledoux** [comment]
done in 5e9f626517ce4943e61865bc11f751aca813ad4f
